name: ComSec
favicon: null
layout_spectrum: 0.75131
typography_spectrum: 0.15096
title: Technical Surveillance Countermeasures - TSCM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c1202b'
    - '#ffffff'
    - '#b3b3b3'
    - '#373435'
  brandStrength: 0.9875271322671324
  lightness: 0.007040070602670312
  saturation: 0.10014473972842097
  rhythmicContrast: 0.5880292186047882
purpose: []
